Transferrable UInt8Array/ArrayBuffer, an `Init` type for channel workers, no `Send` requirement for request and response types.
Jinxit/leptos_workers pull request #54
Opened 2024-07-26 16:20 UTC by zakstucke

Cool library. 

Pretty much as per title. Sorry there are a few things in one, I was adding things I needed for my usecase as I went!

- The `WorkerRequest` layer has gone, the event enum is now part of the `TransferableMessage` layer and also applies to responses, it seems to work a little nicer.
- The channel workers now take an extra initial `Init` type, this makes that worker much more ergonomic and could theoretically in the future be the only worker implementation in the crate. With an init type it covers single request multi response much more easily, and is more ergonomic than the stream implementation imo. 
- Exports a new `Transferable` wrapper for js values, hence the need to remove the `Send` requirement. It has a "magic" serde implementation that separates in and out the js objects during the transfer as part of the `TransferableMessage` layer. At the moment I've just implemented it for `ArrayBuffer` and `UInt8Array`, but can easily be extended for all applicable types: files, blobs etc.

In terms of breaking changes, the only one here I think is the extra initial param for channel workers.

Tested with cargo, wasm-pack and clippy.

2024-07-27 10:27 UTC, Jinxit commented
these changes all sound sick, thanks for contributing. i'll give it a look

2024-07-28 10:16 UTC, Jinxit requested changes
thanks again for contributing, this is really cool and something i pushed off in my mind when building the library in the first place

what you've got here is a really clever way of extracting the Transferables - just a bit _too_ clever for my taste. if you like my idea with the Visitor/DeserializeSeed variant and it works i'd be chuffed, but if that's a dead end i'd be ok with merging this variant as well

2024-07-28 10:16 UTC, Jinxit commented on leptos_workers/src/workers/transferable.rs
> +pub(crate) struct TransferableMessage {
the name of these structs threw me off a bit. i think i would rather have this be just `Message` or `WorkerMessage` or something (essentially like the now removed `WorkerRequest` struct), because it doesn't necessarily even have any Transferables in it, and it's _also_ holding on to normal non-transferable objects that were just serialized (to JsValues).

the same goes for `TransferableMessageType`, which would then be `MessageType` or `WorkerMessageType`. my reasoning is that it's the type of the message, not the type of transferable that the message is or a transferable version of the message type. and without punctuation you can't know if it's `(TransferableMessage)Type` or `Transferable(MessageType)` or even `Transferable(Message)Type`

2024-07-28 10:16 UTC, Jinxit commented on leptos_workers/src/workers/transferable.rs
> +    /// therefore must be passed as a callback.
either this comment is outdated or i'm lost. i don't see any callbacks?

2024-07-28 10:16 UTC, Jinxit commented on leptos_workers/src/workers/transferable.rs
> +    fn post_inner(self) -> (js_sys::Array, js_sys::Array) {
i would also prefer a struct with named fields for the return value just so the two values can't be mixed up, even if it's immediately deconstructed

2024-07-29 13:46 UTC, zakstucke commented on leptos_workers/tests/worker.rs
> +    _init: TestInit,
Not sure what you mean on this one. Anyhow, I've made `init` optional now, so that example omits init entirely.

2024-07-29 13:47 UTC, zakstucke commented on leptos_workers/src/workers/transferable.rs
> +    /// therefore must be passed as a callback.
Was outdated

2024-07-30 07:37 UTC, Jinxit requested changes
really loving the changes. the serialization is a lot simpler, deserialization is just a function call, great convenience stuff around vec/option etc.

all i want now is a couple of unit tests, there's a few integration tests already but it would be nice to test the more complex parts individually

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/transferable_types/base.rs
> +/// along with the most common derivatives like [`js_sys::Uint8Array`]. types are implemented by leptos_workers internally.
i think some extra words slipped in here inbetween edits

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/transferable_types/base.rs
> +/// [`Vec<T>`], [`std::collections::HashMap<String, T>`], [`Option<T>`] are also implemented, as long as T implements [`TransferableType`].
👌

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/transferable_types/base.rs
> +/// All basic types supporting transfers mentioned in mozilla docs are built-in,
are they? or do you mean to add the missing ones before merge?

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/transferable_types/base.rs
> +    fn underlying_transfer_object(&self) -> Vec<JsValue>;
```suggestion
    fn underlying_transfer_objects(&self) -> Vec<JsValue>;
```
now that it returns a vec

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/transferable_types/base.rs
> +    fn to_js_value(&self) -> JsValue;
```suggestion
    /// Convert into a generic js value.
    fn to_js_value(&self) -> JsValue;
    
    /// Convert the type from a generic js value back to the specialized type.
    fn from_js_value(value: JsValue) -> Self;
```

to before from feels more logical to me when reading it top to bottom

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/transferable_types/mod.rs
> +mod rust_wrappers;
```suggestion
mod containers;
```
maybe?

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/worker_message.rs
> +    /// therefore must be passed as a callback.
this is still mentioning a callback that i'm not seeing

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/plumbing/init_workers.rs
> +                // Never received this side.
panic here imo, just so any future mistakes are caught

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/tests/worker.rs
> +    mut init: TestInit,
🎉

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/tests/worker.rs
> +pub async fn channel_worker_no_init(
nice!

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/tests/worker.rs
> +struct TestTransferableMsg(#[serde(with = "leptos_workers::transferable")] Vec<js_sys::Uint8Array>);
i have no doubt it works but maybe try a more complex nested struct too to show that it recurses and finds all the transferables. i don't think we need to require a certain ordering, as long as the vec has the right length and all the right transferables are extracted

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/tests/worker.rs
> +/// The response uses the same transferable objects, checking re-use works too.
good test case

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers_macro/src/v2/analyze.rs
> +        [pub] [async] fn worker(init: Init, rx: leptos_workers::Receiver<Request>, tx: leptos_workers::Sender<Response>)
```suggestion
        [pub] [async] fn worker([init: Init,] rx: leptos_workers::Receiver<Request>, tx: leptos_workers::Sender<Response>)
```
since that's how optional pub/async is represented anyways

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers_macro/src/v2/analyze.rs
> +#[allow(clippy::too_many_lines)]
this lint is probably correct actually but i'm ok with merging it as it is and letting future me refactor it

2024-07-30 07:37 UTC, Jinxit commented on leptos_workers/src/messages/transferable_types/rust_wrappers.rs
> +}
some simple unit tests would be nice

2024-07-30 07:38 UTC, Jinxit commented on leptos_workers/src/workers/transferable.rs
> +}
this still applies though the code is in a different place now

2024-07-30 15:48 UTC, zakstucke commented on leptos_workers/src/messages/transferable_types/base.rs
> +/// All basic types supporting transfers mentioned in mozilla docs are built-in,
yeah I'm going to add them

2024-07-30 15:49 UTC, zakstucke commented on leptos_workers/src/messages/worker_message.rs
> +    /// therefore must be passed as a callback.
Oops

2024-07-30 15:51 UTC, zakstucke commented on leptos_workers/src/plumbing/init_workers.rs
> +                // Never received this side.
Added back, I'd removed because it generates a clippy warning, ignoring warning.

2024-07-31 09:10 UTC, Jinxit commented on leptos_workers/tests/worker.rs
> +async fn test_transferable_whilst_contended() {
confirming that this is an issue with (probably) PoolExecutor, not related to this PR

2024-07-31 16:01 UTC, merged